# Generated by Django 3.1 on 2020-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('clr', models.CharField(max_length=20)),
                ('gametype', models.CharField(default='color-based', max_length=50)),
                ('playedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
