# Generated by Django 3.1 on 2020-08-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('clr', models.CharField(max_length=20)),
                ('gametype', models.CharField(default='color-based', max_length=50)),
                ('playedTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
